apiVersion: v1
kind: Service
metadata:
  name: as-service
spec:
  type: NodePort
  ports:
    - port: 53533
      nodePort: 30001
      protocol: UDP
  selector:
    app: as

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: as-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: as
  template:
    metadata:
      labels:
        app: as
    spec:
      containers:
      - name: as
        image: alexqzh23/as
        ports:
        - containerPort: 53533
          protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: fs-service
spec:
  type: NodePort
  ports:
    - port: 9090
      nodePort: 30002
  selector:
    app: fs

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fs
  template:
    metadata:
      labels:
        app: fs
    spec:
      containers:
      - name: fs
        image: alexqzh23/fs
        ports:
        - containerPort: 9090

---
apiVersion: v1
kind: Service
metadata:
  name: us-service
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30003
  selector:
    app: us

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: us-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: us
  template:
    metadata:
      labels:
        app: us
    spec:
      containers:
      - name: us
        image: alexqzh23/us
        ports:
        - containerPort: 8080